const DISCORD_MESSAGE_SAFE_MAX_LENGTH = 1900;
const DISCORD_SELECT_LABEL_MAX_LENGTH = 100;
const DISCORD_SELECT_LABEL_TRUNCATE_LENGTH = 97;
const QUEUE_PREVIEW_LINE_CLAMP_MAX_LENGTH = 140;
const QUEUE_PREVIEW_LINE_CLAMP_SLICE_LENGTH = 137;

const DEV_LOG_INSPECT_DEPTH = 2;
const DEV_LOG_INSPECT_BREAK_LENGTH = 80;

const YOUTUBE_SEARCH_DEFAULT_LIMIT = 5;
const YOUTUBE_SEARCH_MIN_SECONDS = 30;
const YOUTUBE_MATCH_DEFAULT_MIN_TITLE_RATIO = 0.5;
const YOUTUBE_MATCH_DEFAULT_MIN_ARTIST_RATIO = 0.5;
const SPOTIFY_YOUTUBE_MIN_TITLE_RATIO = 0.6;
const SPOTIFY_YOUTUBE_MIN_ARTIST_RATIO = 1;
const DEFAULT_TRACK_RESOLVER_HTTP_TIMEOUT_MS = 12000;
const DEFAULT_YTDLP_STREAM_TIMEOUT_MS = 12000;
const DEFAULT_SOUND_CLOUD_REDIRECT_MAX_HOPS = 5;
const DEFAULT_PLAYBACK_LOADING_MESSAGE_DELAY_MS = 1000;
const DEFAULT_NOW_PLAYING_PROGRESS_INTERVAL_MS = 4000;
const DEFAULT_NOW_PLAYING_PROGRESS_INITIAL_DELAY_MS = 2000;
const DEFAULT_SEARCH_CHOOSER_MAX_RESULTS = 5;
const DEFAULT_QUEUE_VIEW_PAGE_SIZE = 10;
const DEFAULT_QUEUE_VIEW_TIMEOUT_MS = 300000;
const DEFAULT_QUEUE_MOVE_MENU_PAGE_SIZE = 25;
const DEFAULT_QUEUE_INACTIVITY_TIMEOUT_MS = 300000;
const DEFAULT_INTERACTION_TIMEOUT_MS = 45000;

module.exports = {
  DEFAULT_INTERACTION_TIMEOUT_MS,
  DEFAULT_NOW_PLAYING_PROGRESS_INITIAL_DELAY_MS,
  DEFAULT_NOW_PLAYING_PROGRESS_INTERVAL_MS,
  DEFAULT_PLAYBACK_LOADING_MESSAGE_DELAY_MS,
  DEFAULT_QUEUE_INACTIVITY_TIMEOUT_MS,
  DEFAULT_QUEUE_MOVE_MENU_PAGE_SIZE,
  DEFAULT_QUEUE_VIEW_TIMEOUT_MS,
  DEFAULT_QUEUE_VIEW_PAGE_SIZE,
  DEFAULT_SEARCH_CHOOSER_MAX_RESULTS,
  DEFAULT_SOUND_CLOUD_REDIRECT_MAX_HOPS,
  DEFAULT_TRACK_RESOLVER_HTTP_TIMEOUT_MS,
  DEFAULT_YTDLP_STREAM_TIMEOUT_MS,
  DEV_LOG_INSPECT_BREAK_LENGTH,
  DEV_LOG_INSPECT_DEPTH,
  DISCORD_MESSAGE_SAFE_MAX_LENGTH,
  DISCORD_SELECT_LABEL_MAX_LENGTH,
  DISCORD_SELECT_LABEL_TRUNCATE_LENGTH,
  QUEUE_PREVIEW_LINE_CLAMP_MAX_LENGTH,
  QUEUE_PREVIEW_LINE_CLAMP_SLICE_LENGTH,
  SPOTIFY_YOUTUBE_MIN_ARTIST_RATIO,
  SPOTIFY_YOUTUBE_MIN_TITLE_RATIO,
  YOUTUBE_MATCH_DEFAULT_MIN_ARTIST_RATIO,
  YOUTUBE_MATCH_DEFAULT_MIN_TITLE_RATIO,
  YOUTUBE_SEARCH_DEFAULT_LIMIT,
  YOUTUBE_SEARCH_MIN_SECONDS,
};
